export const FETCH_DISHES_REQUEST = 'FETCH_DISHES_REQUEST'
export const FETCH_DISHES_SUCCESS = 'FETCH_DISHES_SUCCESS'
export const FETCH_DISHES_ERROR = 'FETCH_DISHES_ERROR'

export const ADD_DISH_IN_CART = 'ADD_DISH_IN_CART'
