export const FETCH_DISHES_REQUEST = 'FETCH_DISHES_REQUEST'
export const FETCH_DISHES_SUCCESS = 'FETCH_DISHES_SUCCESS'
export const FETCH_DISHES_ERROR = 'FETCH_DISHES_ERROR'

export const ADD_DISH_IN_CART = 'ADD_DISH_IN_CART'
export const DELETE_DISH_FROM_CART = 'DELETE_DISH_FROM_CART'
export const CALCULATE_TOTAL_PRICE = 'CALCULATE_TOTAL_PRICE'

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";