
export const FETCH_DISHES_REQUEST = 'FETCH_DISHES_REQUEST'
export const FETCH_DISHES_SUCCESS = 'FETCH_DISHES_SUCCESS'
export const FETCH_DISHES_ERROR = 'FETCH_DISHES_ERROR'
export const POST_DISH_SUCCESS = 'POST_DISH_SUCCESS'