export const FETCH_DISHES_REQUEST = 'FETCH_DISHES_REQUEST'
export const FETCH_DISHES_SUCCESS = 'FETCH_DISHES_SUCCESS'
export const FETCH_DISHES_ERROR = 'FETCH_DISHES_ERROR'

export const POST_DISH_SUCCESS = 'POST_DISH_SUCCESS'

export const DELETE_DISH_SUCCESS = 'DELETE_DISH_SUCCESS'

export const EDIT_DISH_SUCCESS = 'EDIT_DISH_SUCCESS'

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR'

export const COMPLETE_ORDER_SUCCESS = 'COMPLETE_ORDER_SUCCESS'